import"./assets/styles-Dw4sMSfm.js";import{a}from"./assets/vendor-CJ4cOYKs.js";const o={allCategories:document.querySelector(".categories"),allProducts:document.querySelector(".products"),notFoundDiv:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),input:document.querySelector(".search-form__input"),clearBtn:document.querySelector(".search-form__btn-clear")};function c(t){o.notFoundDiv.classList.toggle(".not-found--visible",t)}function m(){o.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden"}function l(){o.modal.classList.remove("modal--is-open"),document.body.style.overflow=""}o.modal.addEventListener("click",t=>{t.target===o.modal&&l()});o.modalCloseBtn&&o.modalCloseBtn.addEventListener("click",l);a.defaults.baseURL="https://dummyjson.com";async function i(){return(await a.get("/products/category-list")).data}async function r(){const e=await a.get("/products?limit=12&skip=0");return console.log(e.data.products),e.data.products}async function d(t){const e=await a.get(`/products/category/${t}`);return console.log(e.data.products),e.data.products}async function u(t){const e=await a.get(`/products/${t}`);return console.log(e.data),e.data}async function g(t){const e=await a.get(`/products/search?q=${t}`);return console.log(e.data),e.data.products}u(3);function y(t){o.allCategories.innerHTML="";const e=t.map(s=>`<li class="categories__item">
   <button class="categories__btn" type="button">${s}</button>
 </li>`).join("");o.allCategories.innerHTML=e}function n(t){if(t.length===0){o.notFoundDiv.classList.add("not-found--visible");return}o.notFoundDiv.classList.remove("not-found--visible"),o.allProducts.innerHTML="";const e=t.map(s=>`<li class="products__item" data-id="${s.id}">
    <img class="products__image" src="${s.thumbnail}" alt="${s.title}"/>
    <p class="products__title">${s.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${s.brand}</span></p>
    <p class="products__category">Category:${s.category} </p>
    <p class="products__price">Price:${s.price} $</p>
 </li>`).join("");o.allProducts.innerHTML=e}function _(t){o.modalProduct.innerHTML=`<img class="modal-product__img" src="${t.thumbnail}" alt="${t.title}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t.title}</p>
        <ul class="modal-product__tags">${t.tags?.map(e=>`<li class="modal-product__tag">#${e}</li>`).join("")||""}</ul>
        <p class="modal-product__description">${t.description}</p>
        <p class="modal-product__shipping-information">Shipping:${t.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy:${t.returnPolicy}</p>
        <p class="modal-product__price">Price:${t.price} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`}i();async function f(){const e=["All",...await i()];y(e)}f();async function b(){const t=await r();n(t)}b();o.allCategories.addEventListener("click",async t=>{const e=t.target.closest(".categories__btn");if(e)if(e.textContent==="All"){const s=await r();n(s)}else{const s=await d(e.textContent);n(s)}});d();o.allProducts.addEventListener("click",async t=>{const e=t.target.closest("li[data-id]");if(!e)return;const s=e.dataset.id,p=await u(s);_(p),m()});o.searchForm.addEventListener("submit",async t=>{t.preventDefault();const e=o.input.value.trim();if(e)try{const s=await g(e);o.allProducts.innerHTML="",n(s.slice(0,12)),c(s.length===0)}catch(s){console.error(s)}});o.clearBtn.addEventListener("click",async()=>{o.input.value="",o.clearBtn.classList.remove("visible");try{const t=await r();n(t),c(!1)}catch(t){console.error(t)}});o.input.addEventListener("input",()=>{const t=o.input.value.trim().length>0;o.clearBtn.classList.toggle("visible",t)});
//# sourceMappingURL=index.js.map
