import"./assets/styles-Dw4sMSfm.js";import{a as r}from"./assets/vendor-CJ4cOYKs.js";const n={allCategories:document.querySelector(".categories"),allProducts:document.querySelector(".products"),notFoundDiv:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),input:document.querySelector(".search-form__input"),clearBtn:document.querySelector(".search-form__btn-clear"),addToCartBtn:document.querySelector(".modal-product__btn--cart"),addToWishListBtn:document.querySelector(".modal-product__btn--wishlist"),cartCount:document.querySelector("[data-cart-count]")};function i(t){n.notFoundDiv.classList.toggle(".not-found--visible",t)}function a(){return JSON.parse(localStorage.getItem("cart"))||[]}function _(t){const e=a();e.includes(t)||(e.push(t),localStorage.setItem("cart",JSON.stringify(e)))}function f(t){let e=a();e=e.filter(o=>o!==t),localStorage.setItem("cart",JSON.stringify(e))}function d(){const t=n.cartCount,e=a();t.textContent=e.length}function C(){n.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden"}function u(){n.modal.classList.remove("modal--is-open"),document.body.style.overflow=""}n.modal.addEventListener("click",t=>{t.target===n.modal&&u()});n.modalCloseBtn&&n.modalCloseBtn.addEventListener("click",u);function b(t){const e=document.querySelector(".modal-product__btn--cart");if(!e)return;const o=String(t.id),y=a().includes(o);e.textContent=y?"Remove from Cart":"Add to Cart",e.onclick=()=>{a().includes(o)?(f(o),e.textContent="Add to Cart"):(_(o),e.textContent="Remove from Cart"),d()}}r.defaults.baseURL="https://dummyjson.com";async function p(){return(await r.get("/products/category-list")).data}async function l(){const e=await r.get("/products?limit=12&skip=0");return console.log(e.data.products),e.data.products}async function m(t){const e=await r.get(`/products/category/${t}`);return console.log(e.data.products),e.data.products}async function g(t){const e=await r.get(`/products/${t}`);return console.log(e.data),e.data}async function v(t){const e=await r.get(`/products/search?q=${t}`);return console.log(e.data),e.data.products}g(3);function h(t){n.allCategories.innerHTML="";const e=t.map(o=>`<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>`).join("");n.allCategories.innerHTML=e}function c(t){if(t.length===0){n.notFoundDiv.classList.add("not-found--visible");return}n.notFoundDiv.classList.remove("not-found--visible"),n.allProducts.innerHTML="";const e=t.map(o=>`<li class="products__item" data-id="${o.id}">
    <img class="products__image" src="${o.thumbnail}" alt="${o.title}"/>
    <p class="products__title">${o.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${o.brand}</span></p>
    <p class="products__category">Category:${o.category} </p>
    <p class="products__price">Price:${o.price} $</p>
 </li>`).join("");n.allProducts.innerHTML=e}function L(t){n.modalProduct.innerHTML=`<img class="modal-product__img" src="${t.thumbnail}" alt="${t.title}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t.title}</p>
        <ul class="modal-product__tags">${t.tags?.map(e=>`<li class="modal-product__tag">#${e}</li>`).join("")||""}</ul>
        <p class="modal-product__description">${t.description}</p>
        <p class="modal-product__shipping-information">Shipping:${t.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy:${t.returnPolicy}</p>
        <p class="modal-product__price">Price:${t.price} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`}d();p();async function $(){const e=["All",...await p()];h(e)}$();async function S(){const t=await l();c(t)}S();n.allCategories.addEventListener("click",async t=>{const e=t.target.closest(".categories__btn");if(e)if(e.textContent==="All"){const o=await l();c(o)}else{const o=await m(e.textContent);c(o)}});m();n.allProducts.addEventListener("click",async t=>{const e=t.target.closest("li[data-id]");if(!e)return;const o=e.dataset.id,s=await g(o);L(s),b(s),C()});n.searchForm.addEventListener("submit",async t=>{t.preventDefault();const e=n.input.value.trim();if(e)try{const o=await v(e);n.allProducts.innerHTML="",c(o.slice(0,12)),i(o.length===0)}catch(o){console.error(o)}});n.clearBtn.addEventListener("click",async()=>{n.input.value="",n.clearBtn.classList.remove("visible");try{const t=await l();c(t),i(!1)}catch(t){console.error(t)}});n.input.addEventListener("input",()=>{const t=n.input.value.trim().length>0;n.clearBtn.classList.toggle("visible",t)});
//# sourceMappingURL=index.js.map
